"""
Project Euler Problem 2: Even Fibonacci Numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Solution approaches:
1. Brute force - generate all Fibonacci numbers and sum even ones
2. Optimized - only generate even Fibonacci numbers (every 3rd term is even)
3. Matrix exponentiation for very large limits
"""


def sum_even_fibonacci_brute(limit):
    """
    Calculate sum of even Fibonacci numbers not exceeding limit.

    Brute force approach: generate all Fibonacci numbers, sum the even ones.

    Args:
        limit: Upper bound (inclusive)

    Returns:
        Sum of even Fibonacci numbers
    """
    a, b = 1, 2
    total = 0

    while a <= limit:
        if a % 2 == 0:
            total += a
        a, b = b, a + b

    return total


def sum_even_fibonacci_optimized(limit):
    """
    Calculate sum of even Fibonacci numbers using the pattern.

    Observation: In the Fibonacci sequence, every 3rd term is even.
    F(1)=1, F(2)=1, F(3)=2 (even)
    F(4)=3, F(5)=5, F(6)=8 (even)
    F(7)=13, F(8)=21, F(9)=34 (even)

    Even Fibonacci numbers follow their own recurrence:
    E(n) = 4 * E(n-1) + E(n-2)

    Proof: If E(n-2), E(n-1) are consecutive even Fibonacci numbers,
    then E(n) = F(k) where F(k-3) = E(n-2) and F(k-6) = E(n-2 - 1)
    Using: F(n) = 4*F(n-3) + F(n-6) for the even subsequence

    Args:
        limit: Upper bound (inclusive)

    Returns:
        Sum of even Fibonacci numbers
    """
    # First two even Fibonacci numbers
    e1, e2 = 2, 8
    total = 0

    while e1 <= limit:
        total += e1
        e1, e2 = e2, 4 * e2 + e1

    return total


def fibonacci_generator(limit=None, count=None):
    """
    Generator for Fibonacci sequence.

    Args:
        limit: Maximum value (optional)
        count: Maximum number of terms (optional)

    Yields:
        Fibonacci numbers
    """
    a, b = 1, 1
    generated = 0

    while True:
        if limit is not None and a > limit:
            break
        if count is not None and generated >= count:
            break

        yield a
        a, b = b, a + b
        generated += 1


def even_fibonacci_generator(limit=None, count=None):
    """
    Generator for even Fibonacci numbers only.

    Uses the recurrence E(n) = 4*E(n-1) + E(n-2)

    Args:
        limit: Maximum value (optional)
        count: Maximum number of terms (optional)

    Yields:
        Even Fibonacci numbers
    """
    e1, e2 = 2, 8
    generated = 0

    while True:
        if limit is not None and e1 > limit:
            break
        if count is not None and generated >= count:
            break

        yield e1
        e1, e2 = e2, 4 * e2 + e1
        generated += 1


def binet_fibonacci(n):
    """
    Calculate nth Fibonacci number using Binet's formula.

    F(n) = (phi^n - psi^n) / sqrt(5)
    where phi = (1 + sqrt(5)) / 2 (golden ratio)
    and psi = (1 - sqrt(5)) / 2

    Note: Due to floating-point precision, this is only accurate for small n.

    Args:
        n: Index in Fibonacci sequence (1-indexed)

    Returns:
        Approximate nth Fibonacci number
    """
    import math

    sqrt5 = math.sqrt(5)
    phi = (1 + sqrt5) / 2
    psi = (1 - sqrt5) / 2

    return int(round((phi ** n - psi ** n) / sqrt5))


if __name__ == "__main__":
    print("=" * 60)
    print("Project Euler Problem 2: Even Fibonacci Numbers")
    print("=" * 60)

    # Show the sequence
    print("\nFirst 15 Fibonacci numbers:")
    fibs = list(fibonacci_generator(count=15))
    print(fibs)

    print("\nEven Fibonacci numbers (marked with *):")
    for i, f in enumerate(fibs, 1):
        marker = " *" if f % 2 == 0 else ""
        print(f"F({i}) = {f}{marker}")

    # Example: Below 100
    print("\n" + "-" * 60)
    print("Example: Sum of even Fibonacci numbers <= 100")
    print("-" * 60)

    even_fibs_100 = list(even_fibonacci_generator(limit=100))
    print(f"Even Fibonacci numbers: {even_fibs_100}")
    print(f"Sum: {sum(even_fibs_100)}")

    # Problem: Below 4 million
    print("\n" + "-" * 60)
    print("Problem: Sum of even Fibonacci numbers <= 4,000,000")
    print("-" * 60)

    brute_result = sum_even_fibonacci_brute(4_000_000)
    optimized_result = sum_even_fibonacci_optimized(4_000_000)

    print(f"Brute force result: {brute_result}")
    print(f"Optimized result: {optimized_result}")
    print(f"Results match: {brute_result == optimized_result}")

    # Show the even Fibonacci numbers
    even_fibs = list(even_fibonacci_generator(limit=4_000_000))
    print(f"\nEven Fibonacci numbers <= 4,000,000:")
    print(even_fibs)

    print("\n" + "=" * 60)
    print(f"ANSWER: {optimized_result}")
    print("=" * 60)
